// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package album

import (
	"context"
	v1 "taylor-music-back/api/album/v1"
	"taylor-music-back/internal/service"
)

func (c *ControllerV1) EditAlbum(ctx context.Context, req *v1.EditAlbumReq) (res *v1.EditAlbumRes, err error) {
	err = service.Album().EditAlbum(ctx, req)
	if err != nil {
		return nil, err
	}
	return &v1.EditAlbumRes{
		Message: "编辑成功",
		Code:    200,
	}, nil
}
