// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package album

import (
	"context"
	"taylor-music-back/api/album/v1"
	"taylor-music-back/internal/service"
)

func (c *ControllerV1) CreateAlbum(ctx context.Context, req *v1.CreateAlbumRequest) (res *v1.CreateAlbumResponse, err error) {
	err = service.Album().CreateAlbum(ctx, req)
	if err != nil {
		return nil, err
	}
	return &v1.CreateAlbumResponse{
		Message: "创建成功",
		Code:    200,
	}, nil
}
