// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package song

import (
	"taylor-music-back/api/song"
)

type ControllerV1 struct{}

func NewV1() song.ISongV1 {
	return &ControllerV1{}
}
