// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"taylor-music-back/internal/dao/internal"
)

// albumsDao is the data access object for the table albums.
// You can define custom methods on it to extend its functionality as needed.
type albumsDao struct {
	*internal.AlbumsDao
}

var (
	// Albums is a globally accessible object for table albums operations.
	Albums = albumsDao{internal.NewAlbumsDao()}
)

// Add your custom methods and functionality below.
