// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"taylor-music-back/internal/dao/internal"
)

// songsDao is the data access object for the table songs.
// You can define custom methods on it to extend its functionality as needed.
type songsDao struct {
	*internal.SongsDao
}

var (
	// Songs is a globally accessible object for table songs operations.
	Songs = songsDao{internal.NewSongsDao()}
)

// Add your custom methods and functionality below.
