// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"taylor-music-back/internal/dao/internal"
)

// songStoriesDao is the data access object for the table song_stories.
// You can define custom methods on it to extend its functionality as needed.
type songStoriesDao struct {
	*internal.SongStoriesDao
}

var (
	// SongStories is a globally accessible object for table song_stories operations.
	SongStories = songStoriesDao{internal.NewSongStoriesDao()}
)

// Add your custom methods and functionality below.
